### ISSUE TITLE
Snag a domain

### ISSUE THREAD

**Issue by psstmatt** [RestaurantHealth/RestaurantHealth#10]
[Here's a list](https://domainr.com/ew.io?q=ew) of domain names for ew. I like ew.io and it'll be expiring in September. I liked the .co at first, but then I typed ew.io with my keyboard and they're aligned in perfect mirrior fashion on your keyboard.

[We also have options](https://domainr.com/ew.app?q=ew-app) which are more likely (and available) for "ew-app".

**Comment by bbodenmiller** [comment]
Do we think the name "Ew" is going to work? Seems like the reverse of our goal to find restaurants that aren't bad.

**Comment by psstmatt** [comment]
I've purchased ew-app.com

**Comment by psstmatt** [comment]
I think it has a unique market/brand fit. A cursory search for restaurant health/rating and several other variations bring back many products of low value/quality. When searching for "ew app" I find a few entertainment related products which demonstrates this naming conventions SEO opportunity. 

I'm definitely open to something else. However, "Ew" is a frontrunner if it's only competition is "Resturant Health".

**Comment by bbodenmiller** [comment]
You've got me convinced for now. How do you use Ew in a sentence?

Did you Ew it?
What's the Ew rating?

**Comment by psstmatt** [comment]
I think you've nailed it. “Ew” is an action verb.

**Comment by bbodenmiller** [comment]
So if that's how we use Ew, do you think we want a high or low rating to mean the place is safe to eat at?

**Comment by timdenney** [comment]
"I found it on Ew"
"I was eating happily until I finally Ew'ed"
"Normally, I just ew at my school's cafeteria food, but now I have reason
to double Ew"
"Shit happens, then you Ew"

**Comment by tim-c-larson** [comment]
I think ew factor should be high.. Meaning bad place to eat at

**Comment by psstmatt** [comment]
The Ew thing is a branding exercise. The end game is to make restaurant health standards accessible. And quickly. If that's on a 0-100 scale, letter-based rating, or a narrow Ew/Safe rating that's fine. I like going all in on it and inverting the scale to coincide with a negative connotation.

**Comment by bbodenmiller** [comment]
> The end game is to make restaurant health standards accessible. And quickly.

Totally agree. Let's move the Ew rating discussion to #6.
