### ISSUE TITLE
Refactor to Bootstrap 4 Alpha

### ISSUE THREAD

**Issue by psstmatt** [RestaurantHealth/RestaurantHealth#11]
Fuuuuuck, but yea. Exciting times. Yea, BOI, [Bootstrap 4](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/) baby!

**Comment by bbodenmiller** [comment]
How about v1 bootstrap 3, v2 bootstrap 4? That way you can let the alpha and beta work out the kinks and avoid any possible refactoring if they make any more big changes.

**Comment by psstmatt** [comment]
That's def fair. I'll close this issue until v2. :)
