### ISSUE TITLE
ew-listings.html formatting issue

### ISSUE THREAD

**Issue by tim-c-larson** [RestaurantHealth/RestaurantHealth#15]
ew-listings formatting is messed up after correct data is served to template. 
May need css editing / wizardry

**Comment by bbodenmiller** [comment]
Is the site up live somewhere or do I need to just run it locally?

**Comment by tim-c-larson** [comment]
Needs to be run locally (ie python main.py) 

Note I believe the issue is due to looping of the JSON data. 

will need to implement an iterator for the divs. 
See jinja2 lists: http://jinja.pocoo.org/docs/dev/templates/

**Comment by tim-c-larson** [comment]
FIXED SUPER WORKS
